language: python
python:
  - "3.6"
install:
  #- sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
#  - conda config --remove channels defaults
  - conda config --set channel_priority strict
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install -c conda-forge numpy scipy pandas matplotlib jupyter sphinx sphinx_rtd_theme nbsphinx xlrd h5py netCDF4 xarray gdal deprecation xmltodict semver wradlib
  - python setup.py install
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - py.test
  - coverage run --source=cosmicsense -m py.test
after_success:
  - coveralls
sudo: false
