name: cosmicsense-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - xlrd
  - h5py
  - netCDF4
  - xarray
  - gdal
  - deprecation
  - xmltodict
  - semver
  - wradlib
